/* Your SQL answer goes here */

CREATE DATABASE IF NOT EXISTS DB;

USE DB;

-- create table professor
CREATE TABLE IF NOT EXISTS PROFESSOR(
    PROFESSOR_NAME VARCHAR(255) PRIMARY KEY,
    AGE INTEGER NOT NULL,
    CITY VARCHAR(255) NOT NULL
);

-- create table class
CREATE TABLE IF NOT EXISTS CLASS(
    CLASS_NAME VARCHAR(255) PRIMARY KEY,
    PROFESSOR_NAME VARCHAR(255) NOT NULL,
    FOREIGN KEY (PROFESSOR_NAME) REFERENCES PROFESSOR(PROFESSOR_NAME)
);

-- create table students
CREATE TABLE IF NOT EXISTS STUDENTS(
    STUDENT_NAME VARCHAR(255) PRIMARY KEY,
    AGE INTEGER NOT NULL,
    CITY VARCHAR(255) NOT NULL,
    CLASS_NAME VARCHAR(255) NOT NULL,
    FOREIGN KEY (CLASS_NAME) REFERENCES CLASS(CLASS_NAME)
);

INSERT INTO PROFESSOR(
    PROFESSOR_NAME,
    AGE,
    CITY
) VALUES (
    "Rami Sabouni",
    "30",
    "Ottawa"
);

INSERT INTO PROFESSOR(
    PROFESSOR_NAME,
    AGE,
    CITY
) VALUES (
    "Chang",
    "70",
    "Vietnam"
);

INSERT INTO CLASS(
    CLASS_NAME,
    PROFESSOR_NAME
) VALUES (
    "SYSC4504",
    "Rami Sabouni"
);

INSERT INTO CLASS(
    CLASS_NAME,
    PROFESSOR_NAME
) VALUES (
    "SYSC4005",
    "Chang"
);

INSERT INTO STUDENTS(
    STUDENT_NAME,
    AGE,
    CITY,
    CLASS_NAME
) VALUES (
    "Kareem",
    22,
    "Ottawa",
    "SYSC4504"
);

SELECT
    *
FROM
    CLASS;

SELECT
    *
FROM
    STUDENTS;

SELECT
    *
FROM
    PROFESSOR;