all: lab6 thread1 thread2 thread3 thread4 thread7 thread8

lab6:  lab6.c
	gcc -pthread lab6.c -o lab6

thread1:  thread1.c
	gcc -pthread thread1.c -o thread1

thread2:  thread2.c
	gcc -pthread thread2.c -o thread2

thread3:  thread3.c
	gcc -pthread thread3.c -o thread3

thread4: thread4.c
	gcc -pthread thread4.c -o thread4

thread7: thread7.c
	gcc -pthread thread7.c -o thread7

thread8: thread8.c
	gcc -pthread thread8.c -o thread8